"""Modify Artifact fields and remove language_code

Revision ID: 4cdf5b947d90
Revises: d8c5815bb5b6
Create Date: 2025-08-04 10:03:02.083362

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4cdf5b947d90'
down_revision: Union[str, Sequence[str], None] = 'd8c5815bb5b6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
