"""Modify Artifact fields and remove language_code

Revision ID: c5974f45e514
Revises: 4cdf5b947d90
Create Date: 2025-08-04 10:09:44.412929

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c5974f45e514'
down_revision: Union[str, Sequence[str], None] = '4cdf5b947d90'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('artifact', sa.Column('x_coord', sa.Float(), nullable=True))
    op.add_column('artifact', sa.Column('y_coord', sa.Float(), nullable=True))
    op.drop_column('artifact', 'location')
    op.drop_column('artifact_explanation', 'language_code')
    op.drop_column('faq', 'language_code')
    op.drop_column('question', 'language_code')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('question', sa.Column('language_code', sa.VARCHAR(length=10), autoincrement=False, nullable=True))
    op.add_column('faq', sa.Column('language_code', sa.VARCHAR(length=10), autoincrement=False, nullable=True))
    op.add_column('artifact_explanation', sa.Column('language_code', sa.VARCHAR(length=10), autoincrement=False, nullable=True))
    op.add_column('artifact', sa.Column('location', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.drop_column('artifact', 'y_coord')
    op.drop_column('artifact', 'x_coord')
    # ### end Alembic commands ###
