"""initial tables

Revision ID: d8c5815bb5b6
Revises: 
Create Date: 2025-08-01 13:35:18.159297

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'd8c5815bb5b6'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_artifact_artifact_id'), 'artifact', ['artifact_id'], unique=False)
    op.create_index(op.f('ix_artifact_explanation_explanation_id'), 'artifact_explanation', ['explanation_id'], unique=False)
    op.create_index(op.f('ix_exhibition_exhibition_id'), 'exhibition', ['exhibition_id'], unique=False)
    op.create_index(op.f('ix_faq_faq_id'), 'faq', ['faq_id'], unique=False)
    op.create_index(op.f('ix_gallery_gallery_id'), 'gallery', ['gallery_id'], unique=False)
    op.alter_column('question', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.create_index(op.f('ix_question_question_id'), 'question', ['question_id'], unique=False)
    op.alter_column('user_artwork', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.create_index(op.f('ix_user_artwork_artwork_id'), 'user_artwork', ['artwork_id'], unique=False)
    op.alter_column('users', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.create_index(op.f('ix_users_user_id'), 'users', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_user_id'), table_name='users')
    op.alter_column('users', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.drop_index(op.f('ix_user_artwork_artwork_id'), table_name='user_artwork')
    op.alter_column('user_artwork', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.drop_index(op.f('ix_question_question_id'), table_name='question')
    op.alter_column('question', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.drop_index(op.f('ix_gallery_gallery_id'), table_name='gallery')
    op.drop_index(op.f('ix_faq_faq_id'), table_name='faq')
    op.drop_index(op.f('ix_exhibition_exhibition_id'), table_name='exhibition')
    op.drop_index(op.f('ix_artifact_explanation_explanation_id'), table_name='artifact_explanation')
    op.drop_index(op.f('ix_artifact_artifact_id'), table_name='artifact')
    # ### end Alembic commands ###
